### ISSUE TITLE
F Infrastructure: documentation

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/brightway2#36]
Documentation needs to be reworked and improved. A more decoupled organization of the Brightway 3 libraries should also make (new) contributions easier.

Specific tasks:

- [x] F1 [Develop new Sphinx template with a three column layout](https://github.com/brightway-lca/brightway2/issues/37)
- [ ] F2 [Reorganize documentation following the Diataxis framework for technical documentation](https://github.com/brightway-lca/brightway2/issues/38)
- [ ] F3 [Each notebook (where possible) should link to a *try.brightway.dev* container](https://github.com/brightway-lca/brightway2/issues/39)
- [ ] F4 [Develop, document, and test contribution guidelines and coding styles, and apply to all libraries](https://github.com/brightway-lca/brightway2/issues/40)

**Comment by michaelweinold** [comment]
More than just completed, right, @cmutel? 😇
